-- MySQL Script generated by MySQL Workbench
-- 06/13/14 10:43:34
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_baza_ksiegowa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_baza_ksiegowa` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `db_baza_ksiegowa` ;

-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`kontrachenci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`kontrachenci` (
  `id_kontrachenta` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  `nazwisko` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  `email` VARCHAR(45) NULL,
  `nr_tel` VARCHAR(45) NULL,
  `adres` VARCHAR(80) NULL,
  PRIMARY KEY (`id_kontrachenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`wydatki_inne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`wydatki_inne` (
  `id_wydatku` INT NOT NULL AUTO_INCREMENT,
  `nazwa_wydatku` VARCHAR(100) NULL,
  `data_wydatku` DATE NULL,
  `wydatek_netto` DECIMAL NULL,
  `wydatek_brutto` DECIMAL NULL,
  `wydatki_innecol` VARCHAR(45) NULL,
  `powod_wydatku` VARCHAR(300) NULL,
  PRIMARY KEY (`id_wydatku`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`transakcje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`transakcje` (
  `id_transakcji` INT NOT NULL AUTO_INCREMENT,
  `nazwa_transakcji` VARCHAR(100) NULL,
  `opis_transakcji` VARCHAR(300) NULL,
  `zakup_netto` DECIMAL NULL,
  `zakup_brutto` DECIMAL NULL,
  `data_zakupu` DATE NULL,
  `sprzedaz_netto` DECIMAL NULL,
  `sprzedaz_brutto` DECIMAL NULL,
  `data_sprzedazy` DATE NULL,
  `koszty_allegro` DECIMAL NULL,
  `koszty_inne` DECIMAL NULL,
  `kontrachenci_id_kontrachenta` INT NOT NULL,
  PRIMARY KEY (`id_transakcji`),
  INDEX `fk_transakcje_kontrachenci_idx` (`kontrachenci_id_kontrachenta` ASC),
  CONSTRAINT `fk_transakcje_kontrachenci`
    FOREIGN KEY (`kontrachenci_id_kontrachenta`)
    REFERENCES `db_baza_ksiegowa`.`kontrachenci` (`id_kontrachenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
