-- MySQL Script generated by MySQL Workbench
-- 06/09/14 22:42:06
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_baza_ksiegowa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_baza_ksiegowa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_baza_ksiegowa` ;

-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`kontrachenci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`kontrachenci` (
  `id_kontrachenta` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  `nazwisko` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  `e_mail` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  `nr_tel` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  `adres` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  PRIMARY KEY (`id_kontrachenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`transakcje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`transakcje` (
  `id_transakcji` INT NOT NULL,
  PRIMARY KEY (`id_transakcji`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`zakupy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`zakupy` (
  `id_zakupu` INT NOT NULL,
  `zakup_netto` DECIMAL NULL,
  `zakup_brutto` DECIMAL NULL,
  `data_zakupu` DATE NULL,
  `id_transakcji` INT NOT NULL,
  PRIMARY KEY (`id_zakupu`),
  INDEX `fk_zakupy_transakcje1_idx` (`id_transakcji` ASC),
  CONSTRAINT `fk_zakupy_transakcje1`
    FOREIGN KEY (`id_transakcji`)
    REFERENCES `db_baza_ksiegowa`.`transakcje` (`id_transakcji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`sprzedaze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`sprzedaze` (
  `id_sprzedazy` INT NOT NULL,
  `sprzedaz_netto` DECIMAL NULL,
  `sprzedaz_brutto` DECIMAL NULL,
  `data_sprzedazy` DATE NULL,
  `koszty_allegro` DECIMAL NULL,
  `koszty_inne` DECIMAL NULL,
  `id_kontrachenta` INT NOT NULL,
  `id_transakcji` INT NOT NULL,
  PRIMARY KEY (`id_sprzedazy`),
  INDEX `fk_sprzedaze_kontrachenci_idx` (`id_kontrachenta` ASC),
  INDEX `fk_sprzedaze_transakcje1_idx` (`id_transakcji` ASC),
  CONSTRAINT `fk_sprzedaze_kontrachenci`
    FOREIGN KEY (`id_kontrachenta`)
    REFERENCES `db_baza_ksiegowa`.`kontrachenci` (`id_kontrachenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sprzedaze_transakcje1`
    FOREIGN KEY (`id_transakcji`)
    REFERENCES `db_baza_ksiegowa`.`transakcje` (`id_transakcji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_baza_ksiegowa`.`wydatki_inne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_baza_ksiegowa`.`wydatki_inne` (
  `id_wydatku` INT NOT NULL,
  `data_wydatku` DATE NULL,
  `powod_wydatku` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  PRIMARY KEY (`id_wydatku`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
